version: '3.4'

services:
  rental-server-side:
    build: .
    volumes: 
      - "/Users/upn/Documents/self project/rentalRadar/rentalServerSide:/app:ro"
    ports:
      - "5000:5000"
  crawler:
    build: .
    env_file: 
      - ${ENV_FILE}
  db:
    ports:
      - "3306:3306"
    volumes: 
      - "/Users/upn/Documents/self project/rentalRadar/rentalServerSide/rentalDB:/var/lib/mysql"
      - "/Users/upn/Documents/self project/rentalRadar/rentalServerSide/docker/my.cnf:/etc/mysql/my.cnf:ro"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    # cap_add: 
    #   - SYS_NICE 
