version: '3.4'

services:
  rental-server-side:
    image: andrew54068/rental-server-side:latest
    container_name: rental-server
    ports:
      - "5000:5000"
    restart: always
    env_file: 
      - ${ENV_FILE}
    depends_on: 
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "app.py"]
  crawler:
    image: andrew54068/rental-crawler:latest
    container_name: rental-crawler
    env_file: 
      - ${ENV_FILE}
    depends_on: 
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "Crawler.py"]
  db:
    image: mysql:8.0
    container_name: rental-db
    volumes: 
      - "/home/ec2-user/rentalRadar/mysql:/var/lib/mysql"
      - "/home/ec2-user/rentalRadar/mysql-config/my.cnf:/etc/mysql/my.cnf:ro"
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_SECRET}